#occupancy_grid_config
occupancy_grid_processing:
  occupancy_grid_topic: "/occupancy_grid"
  point_cloud_topic: "/camera/pointcloud"  
  frame_id: "map"
  grid_resolution: 0.1  # Grid cell size in meters
  grid_size: 10000  # Number of cells in each dimension
  grid_origin: (-500.0, -500.0)  # Origin of the grid in meters