#occupancy_grid_config
occupancy_grid_processing:
  # color_image_topic: "/camera/color/image_raw" 
  # depth_image_topic: "/camera/depth/image_raw"
  depth_image_topic: "/davis/left/depth_image_raw" 
  CameraInfo_topic: "/camera/CameraInfo"
  timestamp_topic: "/camera/timestamp"
  #camera_info_topic: "/davis/left/camera_info"
