# rotate_pose_config.yaml
rotate_pose_processing:
  frame_id: "map"
  pose_topic: "/davis/left/pose"
  rotated_pose_topic: "/davis/rotated_pose"
  marker_topic: "path_visualization_marker"
  roll: 277.5    # rotation around x-axis (red axis) in degrees
  pitch: 7.0   # rotation around y-axis (green axis) in degrees
  yaw: 0.0     # rotation around z-axis (blue axis) in degrees
