#segmentation_config
semantic_mapping:
  semantic_map_topic:   "/semantic_map"  # Topic to publish the semantic map
  occupancy_grid_topic: "/occupancy_grid" # Topic to publish the occupancy grid
  point_cloud_topic:    "/camera/pointcloud" # Topic to subscribe the point cloud
  frame_id:             "map" # Frame ID for the map
  prior_prob:           0.5 # Prior probability of occupancy
  occupied_prob:        0.9 # Probability of occupancy given an occupied cell
  free_prob:            0.1 # Probability of occupancy given a free cell
  p_min:                0.2 # Minimum probability for a cell to be considered occupied
  p_max:                0.9 # Maximum probability for a cell to be considered occupied
  # You can run "get_pose_bounds.py" to get the size and grid origin
  grid_resolution:      0.1  # Grid cell size in meters
  grid_width:           3959  # in cells
  grid_height:          3168  # in cells
  grid_origin:          [-100.41, -256.62]  # in meters
  pose_topic:           "/davis/rotated_pose" # Topic to subscribe to pose